"""War initiation — 2d6 + aggression DM each tick per in-contact non-war pair.

War declaration:
  1. Roll 2d6
  2. Add aggression × 6 as a positive DM (range +0 to +6)
  3. If result ≥ WAR_THRESHOLD (default 10), war is declared

The threshold is intentionally high so most polities expand and make contact
before war becomes likely.  High-aggression species (Skharri, Vaelkhi) will
declare war within a few ticks of first contact; low-aggression species
(Golvhaan) may trade maps and coexist for many ticks.

War_name generated by NameGenerator; falls back to "War of Tick N" if no
pool entry is available.
"""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from random import Random

from .events import write_event
from .names import NameGenerator


_WAR_THRESHOLD: int = 10   # 2d6 (range 2–12) + aggression DM 0–6


@dataclass
class WarDeclared:
    polity_a_id: int
    polity_b_id: int
    initiator_id: int
    tick: int
    war_name: str


def war_initiation_roll(
    aggression: float,
    rng: Random,
    extra_dm: int = 0,
) -> bool:
    """Return True if war is declared this tick.

    aggression: 0–1 polity aggression score
    extra_dm: additional positive modifier (provocations, grievances)
    """
    roll = rng.randint(1, 6) + rng.randint(1, 6)
    dm   = int(aggression * 6) + extra_dm
    return (roll + dm) >= _WAR_THRESHOLD


def process_war_rolls(
    conn: sqlite3.Connection,
    tick: int,
    rng: Random,
) -> list[WarDeclared]:
    """Scan ContactRecord for in-contact non-war pairs; roll for war.

    Returns list of newly declared wars.  Updates ContactRecord.at_war and
    inserts WarRecord rows for declared wars.
    """
    rows = conn.execute(
        """
        SELECT cr.contact_id, cr.polity_a_id, cr.polity_b_id,
               pa.aggression AS agg_a, pb.aggression AS agg_b,
               pa.species_id AS sp_a
        FROM   ContactRecord cr
        JOIN   Polity pa ON pa.polity_id = cr.polity_a_id
        JOIN   Polity pb ON pb.polity_id = cr.polity_b_id
        WHERE  cr.at_war = 0
        """,
    ).fetchall()

    declared: list[WarDeclared] = []

    for row in rows:
        a_id   = row["polity_a_id"]
        b_id   = row["polity_b_id"]
        agg_a  = row["agg_a"]
        agg_b  = row["agg_b"]

        # Each side rolls independently; whoever crosses the threshold first
        # is the initiator (if both cross, lower aggression is initiator).
        a_declares = war_initiation_roll(agg_a, rng)
        b_declares = war_initiation_roll(agg_b, rng)

        if not (a_declares or b_declares):
            continue

        initiator = a_id if a_declares else b_id
        if a_declares and b_declares:
            initiator = a_id if agg_a >= agg_b else b_id

        gen = NameGenerator(species_id=row["sp_a"])
        war_name = gen.war(a_id, b_id, tick)

        # Insert WarRecord
        conn.execute(
            """
            INSERT INTO WarRecord
                (polity_a_id, polity_b_id, name, declared_tick, initiator_id)
            VALUES (?, ?, ?, ?, ?)
            """,
            (a_id, b_id, war_name, tick, initiator),
        )

        # Update ContactRecord
        conn.execute(
            "UPDATE ContactRecord SET at_war = 1 WHERE contact_id = ?",
            (row["contact_id"],),
        )

        write_event(
            conn, tick=tick, phase=2,
            event_type="war_declared",
            summary=f"{war_name}: polity {initiator} declares war "
                    f"(polity_a={a_id} polity_b={b_id})",
            polity_a_id=a_id, polity_b_id=b_id,
        )

        declared.append(WarDeclared(
            polity_a_id=a_id, polity_b_id=b_id,
            initiator_id=initiator, tick=tick,
            war_name=war_name,
        ))

    return declared
